
#+TITLE: Emacs Configuration
#+AUTHOR: Tomin Mattam
#+EMAIL: tominjmattam@gmail.com
#+OPTIONS: toc:nil num:nil

* Packages


** Configure =use-package=

  =use-package= to install and configure  packages.

#+begin_src emacs-lisp
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+end_src

Always compile packages, and use the newest version available.

#+begin_src emacs-lisp
  (use-package auto-compile
    :config (auto-compile-on-load-mode))

  (setq load-prefer-newer t)
#+end_src

Disable TLS 1.3; ELPA has higher standards. That'll be the default in Emacs
26.3, I think, but I'm not there yet.

#+begin_src emacs-lisp
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
#+end_src

Disable deprecation warnings about =cl=. The =cl= library has been deprecated, but
lots of packages still use it. I can't control that, but I can disable the
warnings.

#+begin_src emacs-lisp
  (setq byte-compile-warnings '(cl-functions))
#+end_src

* Use =sensible-defaults.el=

Use [[https://github.com/hrs/sensible-defaults.el][sensible-defaults.el]] for some basic settings.

#+begin_src emacs-lisp
  (load-file "~/.emacs.d/sensible-defaults.el/sensible-defaults.el")
  (sensible-defaults/use-all-settings)
  (sensible-defaults/use-all-keybindings)
  (sensible-defaults/backup-to-temp-directory)
#+end_src



* UI


** Pretty Bullets

   #+begin_src emacs-lisp
  (use-package org-bullets
    :init
    (add-hook 'org-mode-hook 'org-bullets-mode))
   #+end_src

** Fancy Downword Arrow

#+begin_src emacs-lisp
  (setq org-ellipsis "⤵")
#+end_src

** Hide Unnecessary Stuff

Hide Slashes and Stars that denote /emphasis/ and *bold* text

#+begin_src emacs-lisp
  (setq org-hide-emphasis-markers t)
#+end_src

Hide tool/menu/scroll bar

#+begin_src emacs-lisp
  (tool-bar-mode 0)
  (menu-bar-mode 0)
  (scroll-bar-mode -1)
#+end_src

Hide tiny scrollbar in mini buffer.


#+begin_src emacs-lisp
  (set-window-scroll-bars (minibuffer-window) nil nil)
#+end_src

Hide Frame Title

#+begin_src emacs-lisp
  (setq frame-title-format '((:eval (projectile-project-name))))
#+end_src



**  Syntax highlighting in source blocks for  editing

#+begin_src emacs-lisp
  (setq org-src-fontify-natively t)
#+end_src

** Press  TAB to switch to language's major mode.

#+begin_src emacs-lisp
  (setq org-src-tab-acts-natively t)
#+end_src

** USe current window than new buffer for editing code snippet

#+begin_src emacs-lisp
  (setq org-src-window-setup 'current-window)
#+end_src

** Quickly insert a block of elisp:

#+begin_src emacs-lisp
  (add-to-list 'org-structure-template-alist
               '("el" . "src emacs-lisp"))
#+end_src

** Don't indent newly expanded blocks

#+begin_src emacs-lisp
  (setq org-adapt-indentation nil)
#+end_src

** Fancy Lambdas

#+begin_src emacs-lisp
  (global-prettify-symbols-mode t)
#+end_src

** Theme


Modu Operandi Theme - From  Harry Swartz Config
#+begin_src emacs-lisp
  (use-package modus-operandi-theme)

  (defun transparency (value)
    "Sets the transparency of the frame window. 0=transparent/100=opaque."
    (interactive "nTransparency Value 0 - 100 opaque:")
    (set-frame-parameter (selected-frame) 'alpha value))

  (defun hrs/apply-theme ()
    "Apply my chosen theme and make frames just slightly transparent."
    (interactive)
    (load-theme 'modus-operandi t)
    (transparency 90))
#+end_src

** Frame Theme

#+begin_src emacs-lisp
  (if (daemonp)
      (add-hook 'after-make-frame-functions
                (lambda (frame)
                  (with-selected-frame frame (hrs/apply-theme))))
    (hrs/apply-theme))
#+end_src

** Use =minions= to hide all minor modes


#+begin_src emacs-lisp
   (use-package minions
     :config
     (setq minions-mode-line-lighter ""
           minions-mode-line-delimiters '("" . ""))
     (minions-mode 1))
#+end_src

** Disable visual bell

This disables the bell altogether.

#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
#+end_src

** Scroll conservatively

 This changes scrolling behavior to only scroll as far as point goes.

#+begin_src emacs-lisp
  (setq scroll-conservatively 100)
#+end_src


* Fonts
